services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - AUTHORIZATION=sk-xxx

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300 chat2api

  cf5s:
    image: dairoot/cf5s:latest
    restart: always
    environment:
      - CHATGPT_GATEWAY_URL=http://chat2api:5005/${API_PREFIX:-}
